spring:
  data:
    mongodb:
      uri: mongodb://localhost/beds
server:
  port: 9003
patient:
  url: http://localhost:9005/patients
  cure:
    Bursting appendix: operation
    common Cold: Mefenamic Acid
    Pneumonia: Macrolide antibiotics
    lupus: Aspirin