server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://localhost/doctor_house_hospital?useSSL=false
    username: dbuser
    password: nacs
  jpa:
    hibernate:
      ddl-auto: update


price:
  treatment:
    x1: 500
    x2: 300
  medicine:
    y1: 600
    y2: 500
