server:
  port: 9004
spring:
  data:
    mongodb:
      uri: mongodb://localhost/patients
patient:
  url: http://localhost:9005/patients

apothecary:
  medicines:
    BurstingAppendix: operation
    commonCold: Mefenamic-Acid
    Pneumonia: Macrolide-antibiotics
    lupus: Aspirin

#  - BurstingAppendix: operation
#  - commonCold: Mefenamic-Acid
#  - Pneumonia: Macrolide-antibiotics
#  - lupus: Aspirin